# Generated by Django 3.0.4 on 2020-04-21 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('BarcodeGround', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=30, verbose_name='商品条码')),
                ('name', models.CharField(max_length=30, verbose_name='商品名称')),
                ('ins_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='生产公司名称')),
                ('ins_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='生产公司地址')),
                ('spec', models.CharField(blank=True, max_length=30, null=True, verbose_name='商品规格')),
                ('price', models.CharField(blank=True, max_length=20, null=True, verbose_name='商品价格')),
                ('image_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='商品图片url')),
                ('goods_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品类型')),
                ('origin', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品原产地')),
                ('brand', models.CharField(blank=True, max_length=50, null=True, verbose_name='商品品牌')),
                ('remark', models.CharField(blank=True, max_length=200, null=True, verbose_name='商品其他信息')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=50, verbose_name='用户昵称')),
                ('openid', models.CharField(max_length=50, verbose_name='用户微信id')),
                ('avatar_url', models.CharField(max_length=200, verbose_name='用户头像url')),
                ('gender', models.IntegerField(blank=True, null=True, verbose_name='用户性别')),
                ('country', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户所在国家')),
                ('province', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户所在省份')),
                ('city', models.CharField(blank=True, max_length=30, null=True, verbose_name='用户所在城市')),
                ('user_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='自定义用户类型')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='用户手机号')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('session_key', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='BarcodeGround.User')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_product', to='BarcodeGround.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to='BarcodeGround.User')),
            ],
        ),
    ]
