version: '3'
services:
  api:
    container_name: api-container
    build: ./backend/
    restart: always
    command: uwsgi -i uwsgi.ini
    volumes:
      - ./backend:/backend
    ports:
      - 8000:8000
  nginx:
    container_name: nginx-container
    build: ./nginx/
    restart: always
    links:
      - "api:api"
    depends_on:
      - api
    ports:
      - 80:80
      - 443:443
    volumes: 
       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
       - ./nginx/cert:/etc/nginx/cert
