# Generated by Django 3.0.4 on 2020-05-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户昵称')),
                ('avatar_url', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户头像url')),
                ('gender', models.IntegerField(blank=True, null=True, verbose_name='用户性别')),
                ('user_type', models.CharField(blank=True, max_length=10, null=True, verbose_name='自定义用户类型')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='用户手机号')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户电子邮箱')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户密码')),
            ],
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=2, verbose_name='验证类型')),
                ('account', models.CharField(max_length=50, verbose_name='验证账户信息')),
                ('code', models.CharField(max_length=10, verbose_name='验证码')),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64)),
                ('session_key', models.CharField(max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_token', to='daily.User')),
            ],
        ),
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('analysis', models.TextField(blank=True, null=True)),
                ('keyword', models.CharField(blank=True, max_length=10, null=True)),
                ('tag', models.CharField(blank=True, max_length=10, null=True)),
                ('ranking', models.IntegerField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dream_user', to='daily.User')),
            ],
        ),
    ]
