# Generated by Django 3.0.4 on 2020-05-19 00:56

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dream',
            name='analysis',
            field=django_mysql.models.JSONField(default=dict),
        ),
    ]
